### ISSUE TITLE
[BUG] Broken Replication

### ISSUE THREAD

**Issue by Valafi** [MikeS-MS/MikesTweaks#16] opened 2023-12-14 09:39 UTC
ModList:
018c66e2-b63b-bcdf-5dc9-b3dc2270ea7a

Where does the issue happen (client-side/host-side/both)?:
Both

Explain the issue in details:
After playing for a while, the clients controls will lock up entirely, leaving us unable to switch inventory slots or even interact with doors/buttons. Additionally, we at one point had a client switching the selected inventory slot also switching the selected slot on the host.

Side note:
I noticed you're not in the Lethal Company Modding Discord. Here's the link in case you're interested: https://discord.gg/XeyYqRdRGC

**Comment by MikeS-MS** [comment] 2023-12-14 10:27
1. Could you send me your console log when the issues happen in a run?
2. Does the issue persist if you just restart the lobby (not the whole game)
3. Could you try running without these mods as a test - LethalLib, LethalThings, HookGenPatcher - to see if the networking issue is gone.

**Comment by Valafi** [comment] 2023-12-15 00:09
My squad won't be available again until this weekend, so I'll have to get back to you on this then. Thanks for looking into this with us.

**Comment by MikeS-MS** [comment] 2023-12-18 00:53
So it turns out this is caused by my mod on its own, not even with any other mods running. 

> Additionally, we at one point had a client switching the selected inventory slot also switching the selected slot on the host.

I narrowed when that happens, I think, it's when you start the game, then host a lobby, then go back to the main screen and rehost again before closing the game. If you end up getting that issue, just restart the game for now, while I find a way to fix it.

> leaving us unable to switch inventory slots or even interact with doors/buttons

This one happens partially for me in the pre-game lobby, by not being able to press escape for some weird reason, although I haven't gotten it to fully lock up all controls like you said as I didn't test for long. I'm uncertain if this part of the issue is due to my mod or some other mod.

**Comment by MikeS-MS** [comment] 2023-12-24 11:15
>Additionally, we at one point had a client switching the selected inventory slot also switching the selected slot on the host.

This will be fixed in 2.0, just finishing up another feature and releasing it.

**Comment by MikeS-MS** [comment] 2023-12-24 13:59
I've pushed out the patch, will keep this issue open for a few days in case something doesn't work correctly and if there's no follow up I will close it. In case you find that there is a problem related to this after I close the issue, you can write back here and I'll reopen it.

**Comment by MikeS-MS** [comment] 2023-12-28 23:19
Closing this due to inactivity, do reply back if the issue persists.

**Closed as completed by MikeS-MS** 2023-12-28 23:19 UTC
Labels: confirmed bug
