### ISSUE TITLE
Item weights are not changed for clients in multiplayer.

### ISSUE THREAD

**Issue by GarethCarew** [MikeS-MS/MikesTweaks#9] opened 2023-11-26 05:01 UTC
When holding items of changed weight (e.g. Shovel, Pro Flashlight, etc), the host has the changed/decreased weight while I (a non-host) have the original weight.

Using version 1.8.0

**Comment by MikeS-MS** [comment] 2023-11-26 08:13
Is MikesTweaks the only mod you're using or are there any others?

**Comment by MikeS-MS** [comment] 2023-11-26 10:30
I've confirmed it does indeed not apply weight changes, should be fixed in the next patch (1.8.2)

**Comment by MikeS-MS** [comment] 2023-11-29 22:59
Closing due to inactivity and behavior working after testing of patch 1.8.2. If the issue persists, create a new issue.

**Closed as completed by MikeS-MS** 2023-11-29 22:59 UTC
Labels: confirmed bug
