### ISSUE TITLE
[BUG] Connected client switching host's inventory slots via hotkeys

### ISSUE THREAD

**Issue by Feathertoes** [MikeS-MS/MikesTweaks#18] opened 2023-12-15 22:44 UTC
**Mods:**
```
 - MikesTweaks - 1.9.1
```
Mod Profile:
018c6fa5-f518-3a86-d1b2-d24cb424d53b

**Configs:**
```
MikesTweaks:
AllowHotbarKeybinds = true
```
**Where does the issue happen (client-side/host-side/both)?:**
Issue happens on host machine and is caused by client

**Explain the issue(s) in detail:**
Connected client using the 1234 inventory slot switch hotkeys is forcefully causing the host to change slots

**Steps for reproducing the issue (optional if you've tested it and found out what causes it):**
https://imgur.com/a/dWpsLAF

**Comment by MikeS-MS** [comment] 2023-12-16 08:59
Does that happen from the start or after a while? I'm asking because I tried reproducing the issue with the modpack you sent me, but it doesn't seem to happen.

**Comment by ureverypie** [comment] 2023-12-17 21:54
It was happening while we were in the pre-game lobby but we never started
Note that all connected players had the mod as well as identical configs so that might have had something to do with it

**Comment by MikeS-MS** [comment] 2023-12-18 00:47
Duplicate of #16

**Closed as completed by MikeS-MS** 2023-12-18 00:47 UTC
Labels: possible bug

**Comment by MikeS-MS** [comment] 2023-12-18 00:53
Monitor #16 for any more info on this
