### ISSUE TITLE
[BUG] have bug when use LMB and F to open flashlight 

### ISSUE THREAD

**Issue by B1ack-1e** [MikeS-MS/MikesTweaks#22] opened 2023-12-26 17:03 UTC
When you add 2 slots to original item slots !
Once you already use left mouse to open flashlight，press F looks like we have double sorts of light。
And when you met this situation，you cannot use 1234 or mouse scroll to change item slots.

**Comment by MikeS-MS** [comment] 2023-12-26 20:00
I need you to give me the information that was in the [template](https://github.com/MikeS-MS/MikesTweaks/blob/main/.github/ISSUE_TEMPLATE/bug-report.md) for the bug report.

**Comment by miguelgdx** [comment] 2023-12-30 22:45
I experienced this too.
The mod seems to now collide with some other mods (or the other way around).
But for the flashlight issue this is how to reproduce it:
1. Have a flashlight (any kind)
2. Press "F" while holding the flashlight
3. You will notice there are now actually two flash beams
4. If you left click or use "F" to deactivate the flashlight, it will deactive one of the light beams, but not all.

I recorded a video where you see it works fine toggling it on and off from another item, but if you do it over the flashlight (pressing F) it will trigger the issue.
- Also "R" key for walkie does not work (I tested it later).
- Also the /toggleVisor command will not work with FOV mod

Here is a collection of mods (code) where you can see it: 018cbce7-27bc-917c-5b71-1247a1182645

https://github.com/MikeS-MS/MikesTweaks/assets/1567609/229b24e2-2584-4d40-b25d-4d3ebcb5a390

**Comment by MikeS-MS** [comment] 2023-12-31 00:05
> I experienced this too. The mod seems to now collide with some other mods (or the other way around). But for the flashlight issue this is how to reproduce it:
> 
> 1. Have a flashlight (any kind)
> 2. Press "F" while holding the flashlight
> 3. You will notice there are now actually two flash beams
> 4. If you left click or use "F" to deactivate the flashlight, it will deactive one of the light beams, but not all.
> 
> I recorded a video where you see it works fine toggling it on and off from another item, but if you do it over the flashlight (pressing F) it will trigger the issue.
> 
> * Also "R" key for walkie does not work (I tested it later).
> * Also the /toggleVisor command will not work with FOV mod
> 
> Here is a collection of mods (code) where you can see it: 018cbce7-27bc-917c-5b71-1247a1182645
> 
>  flashlight_test.mp4

That seems to be a different issue to what the OP was trying to convey. It is similar, although I can't get to the bottom of their issue unless they provide me with the information required on the bug template, like mods they're running, configs that are changed and so on. If your buttons also lock up after this happens then it is the same issue. 

I've tested what you provided me with and now I know what's wrong, for the flashlight at least, this happens with my mod alone, so it's not caused by any other mod, will be fixed in the next patch.

I've no idea about the other 2 problems, will have to keep testing to see what is causing them.

**Comment by MikeS-MS** [comment] 2023-12-31 12:41
@miguelgdx could you create a separate issue and copy-paste the same text from your message there? It's for tracking purposes, because the issues with the walkie and flashlight will be fixed in the next update and might be unrelated to the issue of the op of this issue.

**Comment by miguelgdx** [comment] 2023-12-31 15:02
> @miguelgdx could you create a separate issue and copy-paste the same text from your message there? It's for tracking purposes, because the issues with the walkie and flashlight will be fixed in the next update and might be unrelated to the issue of the op of this issue.

https://github.com/MikeS-MS/MikesTweaks/issues/25

**Comment by MikeS-MS** [comment] 2024-01-12 01:43
Closing due to not enough information and inactivity from op.

**Closed as not planned by MikeS-MS** 2024-01-12 01:43 UTC
Labels: needs more information, possible bug
