### ISSUE TITLE
[BUG] All features of the mod stopped working

### ISSUE THREAD

**Issue by santocraft** [MikeS-MS/MikesTweaks#23] opened 2023-12-30 00:25 UTC
Even tho Mike's is loaded, many if the things it changes like item weight, stamina, day time speed, etc. I don't know what is causing it, here's the main error when starting up the game only!
![image_2023-12-29_192449482](https://github.com/MikeS-MS/MikesTweaks/assets/40782597/4f7e3481-8667-4683-8cd9-ee7d5db06e15)

**Comment by Muki39** [comment] 2023-12-30 01:15
Can confirm that extra inv slots stopped working, as in they do not appear and cannot carry more items then 4

Edited 2023/12/31

R2Modman code
018cc20e-2808-0c5c-75e9-a756a8808b4c

Miketweaks v2.0.1 (issue)
Lethalthings v0.8.8 (maybe conflict?)

For things that could be effecting inv slots tho this wasn't a problem on older version of Miketweaks

LC_API - Disable BundleLoader = true
Miketweaks - Extraitemslots  = 1
Lethalthings - pouchybag enabled = false

Where does the issue happen (client-side/host-side/both)?:
Both

Explain the issue(s) in detail:
Start Game Extra Inv Slots are missing. Flashlight hotkey still works  and from what I can verify weight changes on shop items still work

Steps for reproducing the issue (optional if you've tested it and found out what causes it):
Start New Game (fresh file), or Load Old Save. Player will not  have extra slots

I am not seeing the said error log in console santocraft is having, so for troubleshooting I'm abit lost whats going on will test disabling/enabling other mods in the list 


Tested with the newest version of Miketweaks v2.0.2 issue still persist also attempted to delete configs and just use the new ones that get generated doesn't fix the missing slots

Also sorry for the slow edit don't visit github too regularly

**Comment by Orcaestra** [comment] 2023-12-30 02:04
I have this exact same problem nothing is working

**Comment by MikeS-MS** [comment] 2023-12-30 09:41
Please edit your post to provide all the information that was in the [bug template](https://github.com/MikeS-MS/MikesTweaks/blob/main/.github/ISSUE_TEMPLATE/bug-report.md)

**Comment by MikeS-MS** [comment] 2024-01-03 01:55
@Muki39 Thank you for providing information, I suspect your issue is tied to the compatibility mode with `LethalThings` most likely, it's explained in the readme of my mod and on the thunderstore page for it. I automatically disable my inventory additions when that mod is present, check my comments here #26.

![image](https://github.com/MikeS-MS/MikesTweaks/assets/51383308/9dec5044-d30d-4b29-ac80-e9723093855d)

I also suspect that @santocraft's and @Orcaestra's issue is tied to using `LateGameUpgrades` which is also mentioned in #26 and should be fixed as of v2.0.2., but I can't know for sure until I receive the information I asked for.

**Comment by MikeS-MS** [comment] 2024-01-12 01:42
Closing due to not enough information and inactivity

**Closed as not planned by MikeS-MS** 2024-01-12 01:42 UTC
Labels: needs more information, possible bug
