### ISSUE TITLE
Hotkeys are not working

### ISSUE THREAD

**Issue by maiky93** [MikeS-MS/MikesTweaks#2] opened 2023-11-17 01:24 UTC
none of the added hotkeys seems to be working, 1-9, 'Y', 'U', or 'F' do nothing when ingame, the mod itself works since I have extra slots and the weights seem to be adjusted

**Comment by latemetaI** [comment] 2023-11-17 07:24
I have the same issue. My friends and I all installed the same version. Their key binds work, mine do not.

**Comment by strontix** [comment] 2023-11-18 01:16
help keybinds dont work!

**Comment by ShadowyBerry** [comment] 2023-11-18 08:54
Can attest to this. I have not tried as a client yet, but as a host, neither version 1.4.2 nor 1.5 have working key-binds.
Edit: This only affects the host. If you join as a client, the key-binds work as intended.

**Comment by ByteOfRamen** [comment] 2023-11-19 00:01
I'm just guessing as i don't have experience with unity engine just yet, but could it be that the host has their config set back to default when creating the lobby? Maybe reinitialize the config after server is created? Again i may be saying rubbish but that's my guess of what the issue is.

**Comment by MikeS-MS** [comment] 2023-11-19 14:15
Do they still not work as of 1.6.1? And if so, have you tried regenerating the config file?

**Comment by ShadowyBerry** [comment] 2023-11-19 14:25
Just went in a tested as I only played as a client yesterday. Still the same with 1.6.1 version.

**Comment by MikeS-MS** [comment] 2023-11-19 16:13
Should hopefully be fixed with the next update. @justR4MEN @strontix @latemetaI @maiky93 comment here after I release 1.6.2 if it still doesn't work.

**Comment by MikeS-MS** [comment] 2023-11-22 21:03
Closing due to inactivity, if the issue persists open a new issue.

**Closed as completed by MikeS-MS** 2023-11-22 21:03 UTC
Labels: confirmed bug
